import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Routes, Route } from 'react-router-dom';
import LandingPage from './LandingPage';
import Header from './components/fluent/Header';
import ContentRouter from './components/ContentRouter';
import WPPage from './components/WPPage';
import Accordion from './components/fluent/Accordion';
import FeaturesSection from './components/FeaturesSection';
const Hero = () => (_jsxs("section", { className: "heroSection", children: [_jsx("h1", { className: "heroTitle", children: "HiRed Learning" }), _jsx("p", { className: "heroSubtitle", children: "Secure, cost-effective LMS that fits seamlessly into your Microsoft environment\u2014customisable, scalable, and future-ready" })] }));
const App = () => (_jsxs(_Fragment, { children: [_jsx(Header, {}), _jsx("main", { className: "mainContentWithHeader", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsxs(_Fragment, { children: [_jsx(Hero, {}), _jsx(FeaturesSection, {}), _jsx("section", { className: "homeAccordion", children: _jsx(Accordion, {}) })] }) }), _jsx(Route, { path: "/landing", element: _jsx(LandingPage, {}) }), _jsx(Route, { path: ":type", element: _jsx(ContentRouter, {}) }), _jsx(Route, { path: ":type/:slug", element: _jsx(ContentRouter, {}) }), _jsx(Route, { path: ":parent/:slug", element: _jsx(WPPage, {}) })] }) })] }));
export default App;
